/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: DELL
 *
 * Created on August 28, 2024, 1:16 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE  1

//#define INTERRUPT_PERIOITY_LEVEL_ENABLE            INTERRUPT_FEATURE_ENABLE

#define EXTERNAL_INTERRUPT_INTX_FEARTURE_ENABLE      INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_ONCHANGE_FEARTURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE                 INTERRUPT_FEATURE_ENABLE 

#define TIMER0_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE_ENABLE                INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE                INTERRUPT_FEATURE_ENABLE

#define EUSART_Tx_INTERRUPT_FEATURE_ENABLE           INTERRUPT_FEATURE_ENABLE
#define EUSART_Rx_INTERRUPT_FEATURE_ENABLE           INTERRUPT_FEATURE_ENABLE

#define MSSP_I2C_INTERRUPT_FEATURE_ENABLE            INTERRUPT_FEATURE_ENABLE
#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

